name = "VCF"
uuid = "4aa32d9a-e79d-4ae2-bc49-73d041a2fde6"
authors = ["Rasmus Henningsson <rasmus.henningsson@gmail.com>", "Lund University"]
version = "0.5.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
BGZFStreams = "28d598bf-9b8f-59f1-b38c-5a06b4a0f5e6"
BioCore = "37cfa864-2cd6-5c12-ad9e-b6597d696c81"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"

[compat]
Automa = "0.7, 0.8"
BGZFStreams = "0.3"
BioCore = "2.0.5"
BufferedStreams = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[targets]
test = ["Test", "YAML"]
